export interface CatalogueProduct {
	slug: string;
	number: string;
	title: string;
	category: string;
	description: string;
	sector: string;
	sectorLabel: string;
	type: string;
	typeLabel: string;
	usage: string;
	usageLabel: string;
	customizationFilters: string[];
	customizationLabels: string[];
	applications: string[];
	pieces: string[];
	characteristics: string[];
	sizes: string;
	colors: string;
	fabrics: string;
	production: string;
	image: string;
	imageSmall: string;
	detailImage: string;
	craftImage: string;
	alt: string;
	layout: 'feature' | 'standard' | 'wide';
}

export const catalogueFilters = {
	sectors: [
		{ value: 'education', label: 'Éducation' },
		{ value: 'enterprise', label: 'Entreprise & industrie' },
		{ value: 'hospitality', label: 'Hôtellerie & accueil' },
		{ value: 'healthcare', label: 'Santé & laboratoire' },
		{ value: 'sport', label: 'Sport & associations' },
		{ value: 'ceremony', label: 'Cérémonie & institution' },
		{ value: 'martial', label: 'Arts martiaux' },
		{ value: 'religious-education', label: 'Écoles coraniques' },
		{ value: 'legal', label: 'Juridique' },
		{ value: 'heritage', label: 'Tenues africaines' },
	],
	types: [
		{ value: 'school-uniform', label: 'Uniforme scolaire' },
		{ value: 'professional-wear', label: 'Tenue professionnelle' },
		{ value: 'tailoring', label: 'Blazer & ensemble costume' },
		{ value: 'medical-wear', label: 'Tenue médicale' },
		{ value: 'sportswear', label: 'Tenue sportive' },
		{ value: 'academic-wear', label: 'Toge & tenue académique' },
		{ value: 'martial-arts-wear', label: 'Kimono & entraînement' },
		{ value: 'modest-uniform', label: 'Tenue d’établissement' },
		{ value: 'legal-wear', label: 'Toge juridique' },
		{ value: 'african-tailoring', label: 'Tenue africaine' },
	],
	usages: [
		{ value: 'school', label: 'École & établissement' },
		{ value: 'work', label: 'Travail & service' },
		{ value: 'care', label: 'Soin & laboratoire' },
		{ value: 'team', label: 'Équipe & club' },
		{ value: 'ceremony', label: 'Cérémonie' },
		{ value: 'training', label: 'Entraînement' },
		{ value: 'legal-practice', label: 'Pratique juridique' },
		{ value: 'event', label: 'Événement & tenue de ville' },
	],
	personalization: [
		{ value: 'colors', label: 'Coloris' },
		{ value: 'branding', label: 'Logo & marquage' },
		{ value: 'embroidery', label: 'Broderie' },
		{ value: 'printing', label: 'Impression' },
		{ value: 'cut', label: 'Coupe' },
		{ value: 'sizes', label: 'Tailles' },
		{ value: 'materials', label: 'Matières' },
		{ value: 'labels', label: 'Étiquettes' },
	],
};

/**
 * Gammes présentées comme des pistes de confection, sans prix ni promesses
 * techniques figées : matières, tailles, marquages et volumes sont à confirmer
 * selon le cahier des charges et le devis.
 */
export const catalogueProducts: CatalogueProduct[] = [
	{
		slug: 'uniformes-scolaires',
		number: '01',
		title: 'Tenues scolaires',
		category: 'Uniformes & ensembles d’établissement',
		description: 'Des pièces coordonnées pour les établissements qui souhaitent définir une tenue cohérente avec leur règlement et leur identité.',
		sector: 'education',
		sectorLabel: 'Éducation',
		type: 'school-uniform',
		typeLabel: 'Uniforme scolaire',
		usage: 'school',
		usageLabel: 'École & établissement',
		customizationFilters: ['colors', 'branding', 'embroidery', 'cut', 'sizes', 'materials', 'labels'],
		customizationLabels: ['Coloris de l’établissement', 'Coupe et pièces à définir', 'Logo ou marquage à étudier'],
		applications: ['Écoles primaires et secondaires', 'Établissements privés ou publics', 'Uniformes pour écoles franco-arabes', 'Équipes éducatives et personnels'],
		pieces: ['Uniformes composés de 2 à 5 pièces selon le besoin', 'Chemises, pantalons et cravates', 'Vestes et gilets coordonnés', 'Blousons et tenues d’EPS', 'Jupes, blouses et ensembles scolaires'],
		characteristics: ['Pièces et silhouettes sélectionnées selon le règlement de l’établissement', 'Détails, poches et finitions à préciser au cahier des charges', 'Répartition des tailles à valider avant chiffrage'],
		sizes: 'Grille de tailles, mesures ou gradation à définir avec l’établissement selon les besoins des élèves et des équipes.',
		colors: 'Palette à convenir avec l’établissement en fonction du modèle et des matières retenues.',
		fabrics: 'Tissus à étudier selon l’usage, le confort recherché, l’entretien et les disponibilités.',
		production: 'Le nombre de pièces, la répartition des tailles et le calendrier sont étudiés ensemble puis confirmés sur devis.',
		image: '/images/catalogue/tenues-scolaires-1280.webp',
		imageSmall: '/images/catalogue/tenues-scolaires-640.webp',
		detailImage: '/images/catalogue/tenues-scolaires-detail.webp',
		craftImage: '/images/catalogue/personnalisation-finition.webp',
		alt: 'Élèves en uniformes scolaires bleu marine et ivoire, visuel d’illustration généré',
		layout: 'feature',
	},
	{
		slug: 'tenues-professionnelles',
		number: '02',
		title: 'Tenues professionnelles',
		category: 'Uniformes d’entreprise & vêtements de travail',
		description: 'Des ensembles conçus autour des usages de vos équipes : accueil, service, atelier ou environnement industriel.',
		sector: 'enterprise',
		sectorLabel: 'Entreprise & industrie',
		type: 'professional-wear',
		typeLabel: 'Tenue professionnelle',
		usage: 'work',
		usageLabel: 'Travail & service',
		customizationFilters: ['colors', 'branding', 'embroidery', 'printing', 'cut', 'sizes', 'materials', 'labels'],
		customizationLabels: ['Coloris et coupes selon les postes', 'Logo, broderie ou impression à étudier', 'Poches et détails fonctionnels à définir'],
		applications: ['Entreprises et organisations', 'Équipes d’accueil ou de service', 'Ateliers et environnements de travail'],
		pieces: ['Vestes', 'Pantalons', 'Gilets', 'Combinaisons', 'Chemises et surcouches'],
		characteristics: ['Silhouette et assemblage à adapter à l’activité', 'Détails fonctionnels à cadrer avec les équipes', 'Identification visuelle à étudier selon le support choisi'],
		sizes: 'Tailles individuelles ou répartition par équipe à préciser dans votre demande.',
		colors: 'Coloris harmonisés à votre identité, sous réserve des matières disponibles.',
		fabrics: 'Sélection des matières à étudier selon le poste, l’usage et les contraintes d’entretien.',
		production: 'Les séries, assortiments de modèles et modalités de livraison sont évalués selon votre cahier des charges.',
		image: '/images/catalogue/tenues-professionnelles-1280.webp',
		imageSmall: '/images/catalogue/tenues-professionnelles-640.webp',
		detailImage: '/images/catalogue/tenues-professionnelles-detail.webp',
		craftImage: '/images/catalogue/personnalisation-atelier.webp',
		alt: 'Deux professionnels en vestes et pantalons de travail coordonnés, visuel d’illustration généré',
		layout: 'standard',
	},
	{
		slug: 'tenues-medicales',
		number: '03',
		title: 'Tenues médicales',
		category: 'Blouses, tuniques & vêtements de laboratoire',
		description: 'Des tenues professionnelles pensées pour les environnements de soin et de laboratoire, à préciser selon vos pratiques.',
		sector: 'healthcare',
		sectorLabel: 'Santé & laboratoire',
		type: 'medical-wear',
		typeLabel: 'Tenue médicale',
		usage: 'care',
		usageLabel: 'Soin & laboratoire',
		customizationFilters: ['colors', 'cut', 'sizes', 'materials', 'labels'],
		customizationLabels: ['Coloris et coupes à définir', 'Poches et détails fonctionnels à étudier', 'Matière adaptée à l’usage à sélectionner'],
		applications: ['Infirmiers et infirmières', 'Médecins et équipes médicales', 'Sages-femmes et maternités', 'Cliniques, cabinets et laboratoires'],
		pieces: ['Blouses médicales', 'Tuniques', 'Pantalons médicaux', 'Blouses de laboratoire', 'Ensembles de soin'],
		characteristics: ['Longueur, coupe et rangements à définir selon les usages', 'Coordination possible des pièces d’une même équipe', 'Choix textile à étudier selon le contexte de port'],
		sizes: 'Tailles et mesures à définir selon les équipes concernées.',
		colors: 'Coloris à valider avec votre établissement et selon la disponibilité des matières.',
		fabrics: 'Matières à étudier selon le confort, la tenue et les conditions d’utilisation souhaitées.',
		production: 'Les quantités et répartitions par modèle sont chiffrées après validation du besoin.',
		image: '/images/catalogue/tenues-medicales-1280.webp',
		imageSmall: '/images/catalogue/tenues-medicales-640.webp',
		detailImage: '/images/catalogue/tenues-medicales-detail.webp',
		craftImage: '/images/catalogue/personnalisation-matieres.webp',
		alt: 'Professionnels de santé en blouses et tenues médicales, visuel d’illustration généré',
		layout: 'standard',
	},
	{
		slug: 'tenues-sportives',
		number: '04',
		title: 'Tenues sportives',
		category: 'Maillots, shorts & ensembles d’équipe',
		description: 'Des ensembles coordonnés à définir avec votre club, association ou établissement sportif.',
		sector: 'sport',
		sectorLabel: 'Sport & associations',
		type: 'sportswear',
		typeLabel: 'Tenue sportive',
		usage: 'team',
		usageLabel: 'Équipe & club',
		customizationFilters: ['colors', 'branding', 'embroidery', 'printing', 'cut', 'sizes', 'materials', 'labels'],
		customizationLabels: ['Couleurs d’équipe à définir', 'Logos et marquages à étudier', 'Répartition des tailles à préciser'],
		applications: ['Clubs et associations sportives', 'Équipes scolaires ou institutionnelles', 'Événements et rencontres sportives'],
		pieces: ['Maillots', 'Shorts', 'Survêtements', 'Hauts d’entraînement', 'Ensembles sportifs'],
		characteristics: ['Silhouette et zones de ventilation à préciser selon la discipline', 'Panneaux, empiècements et finitions à définir', 'Coordination visuelle des pièces de l’équipe'],
		sizes: 'Grille de tailles et répartition par joueur à transmettre avec la demande.',
		colors: 'Combinaisons de couleurs à définir selon l’identité de l’équipe et les matières retenues.',
		fabrics: 'Matières à étudier selon la discipline, le confort recherché et la disponibilité.',
		production: 'Composition des lots, tailles et échéances à convenir après étude de votre demande.',
		image: '/images/catalogue/tenues-sportives-1280.webp',
		imageSmall: '/images/catalogue/tenues-sportives-640.webp',
		detailImage: '/images/catalogue/tenues-sportives-detail.webp',
		craftImage: '/images/catalogue/personnalisation-geste.webp',
		alt: 'Équipe en maillots et ensembles sportifs bleu marine et ivoire, visuel d’illustration généré',
		layout: 'standard',
	},
	{
		slug: 'tenues-academiques',
		number: '05',
		title: 'Tenues académiques',
		category: 'Toges, toques & écharpes de cérémonie',
		description: 'Des tenues de cérémonie à composer selon le protocole, les coloris et les besoins de votre établissement.',
		sector: 'ceremony',
		sectorLabel: 'Cérémonie & institution',
		type: 'academic-wear',
		typeLabel: 'Toge & tenue académique',
		usage: 'ceremony',
		usageLabel: 'Cérémonie',
		customizationFilters: ['colors', 'branding', 'embroidery', 'cut', 'sizes', 'materials', 'labels'],
		customizationLabels: ['Coloris et finitions de cérémonie', 'Éléments de personnalisation à étudier', 'Tailles à répartir selon les participants'],
		applications: ['Universités et grandes écoles', 'Étudiants et cérémonies de graduation', 'Masters, doctorants et personnels académiques', 'Cérémonies de remise de diplômes'],
		pieces: ['Toges', 'Toques', 'Écharpes', 'Ensembles de cérémonie'],
		characteristics: ['Drapé et longueur à définir avec l’établissement', 'Éléments de cérémonie à préciser selon le protocole', 'Détails distinctifs à étudier sans présumer d’insignes officiels'],
		sizes: 'Tailles, longueurs et mesures à déterminer selon le modèle et les participants.',
		colors: 'Coloris et éventuels contrastes à valider avec l’établissement.',
		fabrics: 'Matières et finitions à étudier en fonction du tombé et de l’usage cérémoniel.',
		production: 'Les quantités, répartitions et dates de remise sont à confirmer sur devis.',
		image: '/images/catalogue/tenues-academiques-1280.webp',
		imageSmall: '/images/catalogue/tenues-academiques-640.webp',
		detailImage: '/images/catalogue/tenues-academiques-detail.webp',
		craftImage: '/images/catalogue/personnalisation-finition.webp',
		alt: 'Toge académique bleu nuit avec toque et étole dorée, visuel d’illustration généré',
		layout: 'wide',
	},
	{
		slug: 'arts-martiaux',
		number: '06',
		title: 'Arts martiaux',
		category: 'Kimonos & tenues d’entraînement',
		description: 'Des tenues à construire autour des mouvements, du niveau de renfort souhaité et des habitudes de votre discipline.',
		sector: 'martial',
		sectorLabel: 'Arts martiaux',
		type: 'martial-arts-wear',
		typeLabel: 'Kimono & entraînement',
		usage: 'training',
		usageLabel: 'Entraînement',
		customizationFilters: ['colors', 'branding', 'cut', 'sizes', 'materials', 'labels'],
		customizationLabels: ['Coupe et longueur à définir', 'Matière et assemblage à étudier', 'Repères d’équipe à préciser'],
		applications: ['Clubs et associations d’arts martiaux', 'Pratique et entraînement', 'Tenues coordonnées pour une organisation'],
		pieces: ['Kimonos', 'Vestes d’entraînement', 'Pantalons', 'Ensembles personnalisés'],
		characteristics: ['Volume et aisance à définir selon la discipline', 'Assemblages et zones de renfort à étudier dans le cahier des charges', 'Poids et tenue du tissu à préciser avant le devis'],
		sizes: 'Tailles et mesures à déterminer selon le modèle et la discipline pratiquée.',
		colors: 'Coloris à discuter selon les usages et les matières disponibles.',
		fabrics: 'Tissages et poids de matière à étudier au regard des mouvements et de la résistance attendue.',
		production: 'Modèles, tailles, quantités et calendrier sont à évaluer lors de l’étude du projet.',
		image: '/images/catalogue/arts-martiaux-1280.webp',
		imageSmall: '/images/catalogue/arts-martiaux-640.webp',
		detailImage: '/images/catalogue/arts-martiaux-detail.webp',
		craftImage: '/images/catalogue/personnalisation-atelier.webp',
		alt: 'Pratiquant en kimono de judo blanc à l’entraînement, visuel d’illustration généré',
		layout: 'wide',
	},
	{
		slug: 'ecoles-coraniques',
		number: '07',
		title: 'Tenues pour écoles coraniques',
		category: 'Tuniques & tenues d’établissement',
		description: 'Des vêtements d’établissement sobres, confortables et adaptés à un cadre éducatif, selon les choix de chaque école.',
		sector: 'religious-education',
		sectorLabel: 'Écoles coraniques',
		type: 'modest-uniform',
		typeLabel: 'Tenue d’établissement',
		usage: 'school',
		usageLabel: 'École & établissement',
		customizationFilters: ['colors', 'branding', 'cut', 'sizes', 'materials', 'labels'],
		customizationLabels: ['Coupe sobre selon l’établissement', 'Coloris et pièces à convenir', 'Tailles et matières à préciser'],
		applications: ['Écoles coraniques et écoles franco-arabes', 'Tenues coordonnées pour les élèves', 'Vêtements d’établissement selon le règlement défini'],
		pieces: ['Tuniques', 'Pantalons', 'Ensembles', 'Vêtements d’établissement'],
		characteristics: ['Silhouette modeste et sobre à définir avec l’établissement', 'Choix des pièces et détails selon les usages locaux', 'Aucune identité visuelle imposée par le modèle illustratif'],
		sizes: 'Tailles et longueurs à préciser selon l’âge, les mesures et le modèle retenu.',
		colors: 'Palette définie avec l’établissement et confirmée selon les matières disponibles.',
		fabrics: 'Tissus à étudier selon le confort, la saison et l’entretien recherché.',
		production: 'La répartition des pièces, tailles et quantités est cadrée avec l’établissement avant devis.',
		image: '/images/catalogue/ecoles-coraniques-1280.webp',
		imageSmall: '/images/catalogue/ecoles-coraniques-640.webp',
		detailImage: '/images/catalogue/ecoles-coraniques-detail.webp',
		craftImage: '/images/catalogue/personnalisation-matieres.webp',
		alt: 'Élèves en tenues modestes d’établissement, visuel d’illustration généré',
		layout: 'standard',
	},
	{
		slug: 'toges-avocat',
		number: '08',
		title: 'Toges d’avocat',
		category: 'Tenues juridiques & robes de cérémonie',
		description: 'Des tenues juridiques à préciser selon l’usage, les exigences du métier et les détails attendus.',
		sector: 'legal',
		sectorLabel: 'Juridique',
		type: 'legal-wear',
		typeLabel: 'Toge juridique',
		usage: 'legal-practice',
		usageLabel: 'Pratique juridique',
		customizationFilters: ['colors', 'embroidery', 'cut', 'sizes', 'materials', 'labels'],
		customizationLabels: ['Coupe et détails à vérifier selon l’usage', 'Finitions à étudier', 'Mesures à confirmer avant devis'],
		applications: ['Avocats et professionnels du droit', 'Usages institutionnels à préciser', 'Tenues juridiques selon les indications du client'],
		pieces: ['Toges d’avocat', 'Robes juridiques', 'Détails de col et de finition à préciser'],
		characteristics: ['Silhouette formelle et longueur à cadrer selon l’usage', 'Détails de col et parements à vérifier avec le commanditaire', 'Respect des spécifications transmises par le client'],
		sizes: 'Prise de mesures ou grille à définir selon le modèle et les indications du client.',
		colors: 'Coloris et contrastes à confirmer selon les exigences d’usage.',
		fabrics: 'Matières à étudier selon le tombé, le confort et la disponibilité.',
		production: 'Le devis confirme les modalités, quantités et délais après validation des spécifications.',
		image: '/images/catalogue/toges-avocat-1280.webp',
		imageSmall: '/images/catalogue/toges-avocat-640.webp',
		detailImage: '/images/catalogue/toges-avocat-detail.webp',
		craftImage: '/images/catalogue/personnalisation-finition.webp',
		alt: 'Avocate en robe juridique noire et col ivoire, visuel d’illustration généré',
		layout: 'standard',
	},
	{
		slug: 'tenues-africaines',
		number: '09',
		title: 'Tenues africaines',
		category: 'Confection traditionnelle & contemporaine',
		description: 'Des silhouettes traditionnelles ou contemporaines, à définir selon le tissu, la coupe et l’occasion.',
		sector: 'heritage',
		sectorLabel: 'Tenues africaines',
		type: 'african-tailoring',
		typeLabel: 'Tenue africaine',
		usage: 'event',
		usageLabel: 'Événement & tenue de ville',
		customizationFilters: ['colors', 'embroidery', 'cut', 'sizes', 'materials', 'labels'],
		customizationLabels: ['Coupe et finitions à définir', 'Tissu choisi selon le projet', 'Coloris et détails à valider'],
		applications: ['Tenues de cérémonie ou d’événement', 'Silhouettes contemporaines', 'Commandes personnalisées à étudier'],
		pieces: ['Ensembles traditionnels', 'Tenues contemporaines', 'Pièces coordonnées selon la demande'],
		characteristics: ['Coupe et niveau de finition à définir avec le client', 'Tissu et détails à sélectionner selon l’occasion', 'Proposition établie à partir des références fournies'],
		sizes: 'Tailles, mesures et ajustements à déterminer à partir du modèle retenu.',
		colors: 'Coloris définis au regard du tissu et de la direction choisie.',
		fabrics: 'Choix du tissu à préciser avec l’équipe selon la coupe, la tenue et la disponibilité.',
		production: 'Les modalités de confection sont confirmées après étude du modèle, des matières et de la quantité.',
		image: '/images/catalogue/tenues-africaines-1280.webp',
		imageSmall: '/images/catalogue/tenues-africaines-640.webp',
		detailImage: '/images/catalogue/tenues-africaines-detail.webp',
		craftImage: '/images/catalogue/personnalisation-matieres.webp',
		alt: 'Deux silhouettes contemporaines en tenues africaines indigo et ivoire, visuel d’illustration généré',
		layout: 'wide',
	},
	{
		slug: 'tenues-hotellerie',
		number: '10',
		title: 'Tenues d’hôtellerie & d’accueil',
		category: 'Uniformes de service & réception',
		description: 'Des tenues coordonnées pour les équipes d’hôtel, de réception, de restauration et de service.',
		sector: 'hospitality',
		sectorLabel: 'Hôtellerie & accueil',
		type: 'professional-wear',
		typeLabel: 'Tenue professionnelle',
		usage: 'work',
		usageLabel: 'Travail & service',
		customizationFilters: ['colors', 'branding', 'embroidery', 'cut', 'sizes', 'materials', 'labels'],
		customizationLabels: ['Identité et coloris de l’établissement', 'Coupe adaptée aux postes', 'Broderie ou marquage à étudier'],
		applications: ['Hôtels et maisons d’hôtes', 'Réception, restauration et service', 'Équipes d’entretien et d’accueil'],
		pieces: ['Vestes et gilets de réception', 'Chemises et pantalons', 'Tabliers et tenues de service', 'Ensembles coordonnés'],
		characteristics: ['Silhouettes adaptées aux différents métiers de l’établissement', 'Détails et poches à préciser selon les postes', 'Coloris et marquages à harmoniser avec votre identité'],
		sizes: 'Tailles et répartition par équipe à définir selon les modèles retenus.',
		colors: 'Palette à convenir avec l’établissement et les matières disponibles.',
		fabrics: 'Matières à étudier selon le confort, l’entretien et les usages des équipes.',
		production: 'Modèles, quantités et échéances sont précisés au devis selon votre projet.',
		image: '/images/catalogue/tenues-hotellerie-1280.webp',
		imageSmall: '/images/catalogue/tenues-hotellerie-640.webp',
		detailImage: '/images/catalogue/tenues-hotellerie-detail.webp',
		craftImage: '/images/catalogue/personnalisation-atelier.webp',
		alt: 'Réceptionniste en gilet bleu nuit et serveur en tablier ivoire, visuel d’illustration généré',
		layout: 'standard',
	},
	{
		slug: 'blazers-femme-costumes',
		number: '11',
		title: 'Blazers femme & ensembles costume',
		category: 'Tailleur, veste & costume coordonné',
		description: 'Blazers féminins et ensembles costume à composer : veste, gilet, chemise, pantalon et cravate selon le style recherché.',
		sector: 'enterprise',
		sectorLabel: 'Tenue de ville & entreprise',
		type: 'tailoring',
		typeLabel: 'Blazer & ensemble costume',
		usage: 'event',
		usageLabel: 'Événement & tenue de ville',
		customizationFilters: ['colors', 'cut', 'sizes', 'materials', 'labels'],
		customizationLabels: ['Coupe et silhouette à définir', 'Matières et coloris à sélectionner', 'Ensemble à composer selon vos besoins'],
		applications: ['Blazers femme', 'Costumes et ensembles coordonnés', 'Tenues de représentation et événements'],
		pieces: ['Blazer femme', 'Veste de costume', 'Gilet', 'Chemise', 'Pantalon et cravate'],
		characteristics: ['Ensemble de 2 à 5 pièces selon la composition choisie', 'Coupe, doublure et finitions à étudier', 'Possibilité de coordonner plusieurs silhouettes'],
		sizes: 'Tailles et mesures individuelles à préciser avec le modèle choisi.',
		colors: 'Coloris définis selon le style souhaité et les matières disponibles.',
		fabrics: 'Matières à étudier selon le tombé, la saison et l’usage.',
		production: 'Chaque ensemble est évalué selon les pièces, les tailles et les quantités demandées.',
		image: '/images/catalogue/blazers-femme-costumes-1280.webp',
		imageSmall: '/images/catalogue/blazers-femme-costumes-640.webp',
		detailImage: '/images/catalogue/blazers-femme-costumes-detail.webp',
		craftImage: '/images/catalogue/personnalisation-finition.webp',
		alt: 'Deux silhouettes féminines en blazer et ensemble costume bleu nuit ajustés, visuel d’illustration généré',
		layout: 'standard',
	},
];

export const processSteps = [
	{ number: '01', title: 'Votre besoin', text: 'Usage, équipes, quantités et échéance souhaitée.' },
	{ number: '02', title: 'Conception', text: 'Modèle, coupe et détails à cadrer avec vous.' },
	{ number: '03', title: 'Choix des matières', text: 'Tissus et finitions à étudier selon l’usage.' },
	{ number: '04', title: 'Personnalisation', text: 'Coloris et marquages à confirmer selon faisabilité.' },
	{ number: '05', title: 'Production', text: 'Modalités définies après validation du devis.' },
	{ number: '06', title: 'Contrôle qualité', text: 'Points de contrôle adaptés au cahier des charges.' },
	{ number: '07', title: 'Livraison', text: 'Calendrier et modalités confirmés ensemble.' },
];

export const personalizationImages = [
	{
		src: '/images/catalogue/personnalisation-matieres.webp',
		alt: 'Tissus bleu marine et ivoire disposés sur une table de confection, visuel d’illustration généré',
		label: 'Matières & coloris',
	},
	{
		src: '/images/catalogue/personnalisation-atelier.webp',
		alt: 'Machine à coudre et vêtements en cours de finition dans un atelier, visuel d’illustration généré',
		label: 'Assemblage & finitions',
	},
	{
		src: '/images/catalogue/personnalisation-finition.webp',
		alt: 'Détail de finition dorée sur une toge bleu nuit, visuel d’illustration généré',
		label: 'Détails de confection',
	},
];
